export const obj = {
    "words": [
        "apple", "banana", "cherry", "date", "elephant", "flower", "grape", "horizon", "igloo", "jungle",
        "kite", "lemon", "mountain", "nebula", "ocean", "penguin", "quasar", "rainbow", "sunflower", "tornado",
        "umbrella", "volcano", "waterfall", "xylophone", "yogurt", "zeppelin", "abstract", "balance", "courage",
        "diligent", "envelope", "fantasy", "glacier", "harbor", "illusion", "jovial", "kindness", "luminous",
        "mystery", "nostalgia", "optimistic", "paradox", "quintessential", "resilient", "serendipity", "tranquil",
        "universe", "vibrant", "whimsical", "xenophobia", "yearning", "zealous", "adventure", "butterfly",
        "compassion", "determination", "effervescent", "felicity", "gratitude", "harmony", "inspiration", "jubilant",
        "kaleidoscope", "legendary", "mesmerize", "nebulous", "opulent", "phenomenal", "quizzical", "reverence",
        "symphony", "transcendent", "uplifting", "versatile", "wanderlust", "xylophonist", "yonder", "zenith",
        "affection", "benevolent", "charismatic", "delightful", "eloquent", "fascinating", "glistening", "hypnotic",
        "ingenious", "jubilance", "keystone", "labyrinth", "magnificent", "nirvana", "orchestrate", "pristine",
        "quixotic", "radiance", "sensational", "tenacity", "unravel", "valiant", "whisper", "xenial", "youthful",
        "zodiac", "ascend", "brilliant", "captivating", "dauntless", "ecstatic", "fervent", "gargantuan",
        "heartwarming", "idyllic", "jubilation", "knack", "luminescent", "melancholy", "novelty", "overture",
        "paragon", "quintet", "resplendent", "silhouette", "tremendous", "unison", "vivacious", "wondrous",
        "xenogenesis", "yearn", "zen-like", "abundant", "blissful", "courageous", "dedicated", "ephemeral",
        "flourish", "glamorous", "humble", "invincible", "judicious", "knightly", "legend", "meticulous",
        "nostalgic", "omnipotent", "persistence", "quiver", "radiant", "sincere", "triumphant", "unwavering",
        "valiant", "warmhearted", "xanthic", "yawning", "zephyr", "ameliorate", "benevolence", "catalyst",
        "dexterity", "effortless", "fortitude", "gallant", "heroic", "illustrious", "joyous", "kindhearted",
        "limitless", "metamorphosis", "noble", "omniscient", "phenomenon", "quiescent", "resonance", "steadfast",
        "tangible", "unparalleled", "victorious", "whimsical", "xenophile", "yearned", "zealot", "altruistic",
        "bewilder", "chivalrous", "dazzling", "exquisite", "flawless", "gregarious", "hospitable", "idiosyncratic",
        "juxtapose", "knitting", "labyrinthine", "mirthful", "nefarious", "oratorical", "perceptive", "quagmire",
        "rejuvenate", "serenade", "tenacious", "uplift", "vivacity", "wistful", "xenophobic", "yonder", "zestful",
        "aspiration", "buoyant", "candid", "debonair", "exuberant", "felicitous", "gallivant", "hustle",
        "interstellar", "jaunty", "kinetic", "luminous", "monumental", "nurture", "oblivious", "propensity",
        "quirky", "radiate", "serendipitous", "tenderhearted", "unorthodox", "venturesome", "whimsically",
        "xylophonically", "yearlong", "zealously", "arduous", "blazing", "convivial", "dainty", "ethereal",
        "fascinate", "gratuitous", "herculean", "impeccable", "jocund", "kindle", "lucid", "melodious",
        "nonchalant", "obstinate", "paradoxical", "quagmire", "rebellious", "sovereign", "tumultuous",
        "unpredictable", "vortex", "winsome", "xenogeny", "yearly", "zen-like", "aesthetic", "beauteous",
        "charming", "diligence", "enigmatic", "fanciful", "glorious", "humorous", "ingenious", "joyfully",
        "knowledgeable", "leverage", "mystical", "noteworthy", "opalescent", "plentiful", "quizzing",
        "radiantly", "soothing", "tranquility", "universal", "verdant", "wisdom", "xenon", "year-round",
        "zeal", "alluring", "beneficent", "charity", "dignity", "efficacious", "fortuitous", "genuine",
        "hopeful", "immaculate", "jubilantly", "keen", "laudable", "magnanimous", "neighborly", "overture",
        "pragmatic", "quaint", "reliable", "stunning", "thrive", "ubiquitous", "valedictory", "welcoming",
        "xerophilous", "yielding", "zest", "amiable", "blossom", "courteous", "deliberate", "euphoria",
        "fervor", "glowing", "hospitable", "imaginative", "joyous", "kinship", "luscious", "majestic",
        "notable", "ornamental", "picturesque", "quasar", "reminiscent", "serene", "tantalizing",
        "unflinching", "venerated", "wonderment", "xenolith", "yacht", "zephyr", "agility", "bounty",
        "contentment", "daring", "effulgence", "formidable", "gumption", "hallowed", "incandescent",
        "jocular", "kindred", "lively", "magnificent", "nuance", "omnipresent", "profound", "quotient",
        "robust", "sprightly", "thoughtful", "unassuming", "versatility", "welter", "xylotomy", "yawning",
        "zebra"
    ]
}
